import { Eye, EyeOff } from "lucide-react";
const fieldClass=(error)=>`w-full px-4 py-3 rounded-xl border outline-none focus:ring-2 focus:ring-camel transition-colors ${error?"border-rust":"border-ink/15"}`;
export default function RegisterFields({fields,errors,showPassword,setShowPassword,setField}){return <>
 <Field id="register-full-name" label="نام و نام‌خانوادگی" value={fields.fullName} onChange={setField("fullName")} error={errors.fullName} placeholder="مثلاً سارا احمدی"/>
 <Field id="register-email" label="ایمیل" type="email" value={fields.email} onChange={setField("email")} error={errors.email} placeholder="name@gmail.com"/>
 <Field id="register-phone" label="شماره موبایل" type="tel" dir="ltr" value={fields.phone} onChange={setField("phone")} error={errors.phone} placeholder="0912xxxxxxx"/>
 <div><label htmlFor="register-password" className="block text-sm font-bold mb-2 text-ink/70">رمز عبور</label><div className="relative"><input id="register-password" type={showPassword?"text":"password"} value={fields.password} onChange={setField("password")} placeholder="حداقل ۸ کاراکتر" className={fieldClass(errors.password)+" pl-11"}/><button type="button" onClick={()=>setShowPassword((prev)=>!prev)} className="cursor-pointer absolute left-3 top-1/2 -translate-y-1/2 text-ink/40" aria-label={showPassword?"پنهان کردن رمز":"نمایش رمز"}>{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{errors.password&&<p className="text-xs text-rust mt-1.5" role="alert">{errors.password}</p>}</div>
 <Field id="register-confirm-password" label="تکرار رمز عبور" type={showPassword?"text":"password"} value={fields.confirmPassword} onChange={setField("confirmPassword")} error={errors.confirmPassword} placeholder="رمز عبور را دوباره وارد کنید"/>
 <div><label className="flex items-start gap-2 text-sm text-ink/70 cursor-pointer"><input type="checkbox" checked={fields.acceptTerms} onChange={(e)=>setField("acceptTerms")(e.target.checked)} className="accent-forest w-4 h-4 mt-0.5"/><span>قوانین و مقررات رخت‌آرا را می‌پذیرم</span></label>{errors.acceptTerms&&<p className="text-xs text-rust mt-1.5" role="alert">{errors.acceptTerms}</p>}</div>
 </>}
function Field({id,label,error,...props}){return <div><label htmlFor={id} className="block text-sm font-bold mb-2 text-ink/70">{label}</label><input id={id} aria-invalid={Boolean(error)} aria-describedby={error?`${id}-error`:undefined} className={fieldClass(error)} {...props}/>{error&&<p id={`${id}-error`} className="text-xs text-rust mt-1.5" role="alert">{error}</p>}</div>}
